name: First Workflow
on: workflow_dispatch
jobs: 
  myfirst-job:
    runs-on: macos-11
    steps:
      - name: Print greeting
        run:  | 
            echo "Hello World 1!"
            echo "Hello World 2!"            
      - name: Print good bye
        run: echo "Done - bye!"
